### ISSUE TITLE
SVG export does not write file.

### ISSUE THREAD

**Issue by tajaddini** [FOSStriangulator/FOSStriangulator#12]
When trying to export SVG, the console does not log anything and there is no file. Tested on MS Store and stand-alone JAR versions. Also tested different paths, I don't suspect this is a permission issue, other exports are fine.

**Comment by rayman3003** [comment]
I have the same issue. The SVG export doesn't work for me too. [It asks for a name, but it doesn't produce a file] 

Hope the developer solve this serious problem soon.

**Comment by le-jun** [comment]
Six months later, still no idea about the source of the issue?

**Comment by 12people** [comment]
Unfortunately, no.

I'm the sole person working on this project, among other ones, in my free time and right now my focus is elsewhere. To make matters more complicated, I only use Linux and macOS, where this SVG functionality seems to be working for me, so it's hard for me to reproduce this and I have to rely on borrowing others' Windows computers, which isn't particularly conducive to effective development.

It's possible that version 4 of Processing, which is currently in Beta, might fix this.

If anyone reading this knows Java or even just any sort of C-style programming language, Processing is really easy to pick up — it's just a rebrand of Java that's simplified to make graphical operations easy. Feel free to look into it and submit a PR. :)

**Comment by rayman3003** [comment]
> I only use Linux and macOS

U can use virtual machines to simulate windows on linux. like VirtualBox:

https://www.youtube.com/watch?v=OWmD8obq4eQ

> It's possible that version 4 of Processing, which is currently in Beta

I couldn't find any link for windows version of beta v4 of FOSStriangulator. Can u give me a link, So I could try it on windows?

**Comment by 12people** [comment]
@rayman3003 Thanks for the tip. :)

I know about virtual machines, but right now, my current laptop doesn't have nearly enough free space to allow for it.

As for the beta, I meant the beta version of Processing, which is the set of libraries that FOSStriangulator is based on — you can download that on the [official Processing website](https://processing.org/download). To compile FOSStriangulator inside processing, download the FOSStriangulator from this Github repository, open the Processing DE (installed along with the language by the official installer), and open up the FOSStriangulator/FOSStriangulator.pde file.

**Comment by bluefox67** [comment]
Hi 12people,
I downloaded the MS-Version and I have the same problem. Do you plan to fix this inside FOSStriangulator at any time?
Regards, bluefox67

**Comment by 12people** [comment]
It's not a priority for me right now, unfortunately. :/
Anyone here who has some Java experience is welcome to take a look at it, though.

**Comment by 12people** [comment]
I forgot to mention: You can open the PDF file exported by FOSStriangulator in a vector editor (for example, the free and open-source [Inkscape](https://inkscape.org/)) and convert it to SVG that way. Be careful to remove the original photo in the background in Inkscape before exporting.

**Comment by MaurizioPz** [comment]
I'm having the same problem while using the app from MS-Store, but unfortunately wasn't able to reproduce it while running it in the processing IDE (tested both 3 and 4 version).
Maybe is something related to the java version embedded with the app?

So, as a work around at least running from source seems to work.

**Comment by 12people** [comment]
@MaurizioPz Could you try running the jar from https://github.com/FOSStriangulator/FOSStriangulator/releases ? (The FOSStriangulator_jar.zip file.)

I'm wondering whether it's some sort of Microsoft Store problem or whether there's an issue with the jar itself.

**Comment by MaurizioPz** [comment]
Double clicking I get the same behavior. 
I've tried running from console and I get an exception that something is missing from classpath.
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at processing.core.PApplet.selectCallback(PApplet.java:6719)
        at processing.core.PApplet.access$1(PApplet.java:6712)
        at processing.core.PApplet$4.run(PApplet.java:6623)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: The processing.svg.PGraphicsSVG renderer is not in the class path.
        at processing.core.PApplet.makeGraphics(PApplet.java:2311)
        at processing.core.PApplet.createGraphics(PApplet.java:2219)
        at FOSStriangulator.saveSvgPdf(FOSStriangulator.java:1800)
        at FOSStriangulator.svgFileSave(FOSStriangulator.java:1795)
        ... 20 more

I've tried to google my way out of it, but without luck (I haven't done java in a long time). My last attempt was running this command, but nothing changed

 java.exe -classpath batik-awt-util-1.8.jar:batik-dom-1.8.jar:batik-ext-1.8.jar:batik-svggen-1.8.jar:batik-util-1.8.jar:batik-xml-1.8.jar:svg.jar -jar C:\Users\Maurizio\Downloads\FOSStriangulator.jar

**Comment by 12people** [comment]
Thanks, that was very helpful!
It seems like I might accidentally not be bundling PGraphicsSVG in the jar. Either that, or it just doesn't have a functioning Windows implementation.
 
I'll look into it when I find the time.
